import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider } from 'antd'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@radix-ui/themes/styles.css'
import './globals.css'

import { Theme } from '@radix-ui/themes'
import { ThemeProvider } from 'next-themes'
import Header from '@/components/layouts/header/header'
import Footer from '@/components/layouts/footer'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Theme>
                        <Header />
                        <AntdRegistry>
                            <ConfigProvider
                                theme={{
                                    cssVar: true,
                                    token: {
                                        colorText: 'var(--color-foreground)',
                                        colorTextSecondary:
                                            'var(--color-secondary-foreground)',
                                        colorTextDescription:
                                            'var(--color-secondary-foreground)'
                                    }
                                }}
                            >
                                <div className="px-2">{children}</div>
                            </ConfigProvider>
                        </AntdRegistry>
                        <Footer />
                    </Theme>
                </ThemeProvider>
            </body>
        </html>
    )
}
