/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
    export interface Resource {
        NextAuthSecret: {
            type: "sst.sst.Secret";
            value: string;
        };
        UserPool: {
            id: string;
            type: "sst.aws.CognitoUserPool";
        };
        Web: {
            type: "sst.aws.Nextjs";
            url: string;
        };
        WebClient: {
            id: string;
            secret: string;
            type: "sst.aws.CognitoUserPoolClient";
        };
    }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
